const COUNTRIES = [
["Afghanistan","AF"],
["Albania","AL"],
["Algeria","DZ"],
["Andorra","AD"],
["Angola","AO"],
["Antigua and Barbuda","AG"],
["Argentina","AR"],
["Armenia","AM"],
["Australia","AU"],
["Austria","AT"],
["Azerbaijan","AZ"],
["Bahamas","BS"],
["Bahrain","BH"],
["Bangladesh","BD"],
["Barbados","BB"],
["Belarus","BY"],
["Belgium","BE"],
["Belize","BZ"],
["Benin","BJ"],
["Bhutan","BT"],
["Bolivia","BO"],
["Bosnia and Herzegovina","BA"],
["Botswana","BW"],
["Brazil","BR"],
["Brunei Darussalam","BN"],
["Bulgaria","BG"],
["Burkina Faso","BF"],
["Burundi","BI"],
["Cambodia","KH"],
["Cameroon","CM"],
["Canada","CA"],
["Cape Verde","CV"],
["Central African Republic","CF"],
["Chad","TD"],
["Chile","CL"],
["China","CN"],
["Colombia","CO"],
["Comoros","KM"],
["Congo","CG"],
["Costa Rica","CR"],
["Croatia","HR"],
["Cyprus","CY"],
["Czechia","CZ"],
["Denmark","DK"],
["Djibouti","DJ"],
["Dominica","DM"],
["Dominican Republic","DO"],
["Ecuador","EC"],
["Egypt","EG"],
["El Salvador","SV"],
["Equatorial Guinea","GQ"],
["Eritrea","ER"],
["Estonia","EE"],
["Eswatini","SZ"],
["Ethiopia","ET"],
["Fiji","FJ"],
["Finland","FI"],
["France","FR"],
["Gabon","GA"],
["Gambia","GM"],
["Georgia","GE"],
["Germany","DE"],
["Ghana","GH"],
["Greece","GR"],
["Grenada","GD"],
["Guatemala","GT"],
["Guinea","GN"],
["Guyana","GY"],
["Haiti","HT"],
["Honduras","HN"],
["Hong Kong","HK"],
["Hungary","HU"],
["Iceland","IS"],
["India","IN"],
["Indonesia","ID"],
["Iraq","IQ"],
["Ireland","IE"],
["Israel","IL"],
["Italy","IT"],
["Jamaica","JM"],
["Japan","JP"],
["Jordan","JO"],
["Kazakhstan","KZ"],
["Kenya","KE"],
["Kuwait","KW"],
["Kyrgyzstan","KG"],
["Lao People's Democratic Republic","LA"],
["Latvia","LV"],
["Lebanon","LB"],
["Lesotho","LS"],
["Liberia","LR"],
["Libya","LY"],
["Lithuania","LT"],
["Luxembourg","LU"],
["Macao","MO"],
["Madagascar","MG"],
["Malawi","MW"],
["Malaysia","MY"],
["Maldives","MV"],
["Mali","ML"],
["Malta","MT"],
["Mauritania","MR"],
["Mauritius","MU"],
["Mexico","MX"],
["Moldova","MD"],
["Monaco","MC"],
["Mongolia","MN"],
["Montenegro","ME"],
["Morocco","MA"],
["Mozambique","MZ"],
["Myanmar","MM"],
["Namibia","NA"],
["Nepal","NP"],
["Netherlands","NL"],
["New Zealand","NZ"],
["Nicaragua","NI"],
["Niger","NE"],
["Nigeria","NG"],
["North Macedonia","MK"],
["Norway","NO"],
["Oman","OM"],
["Pakistan","PK"],
["Panama","PA"],
["Papua New Guinea","PG"],
["Paraguay","PY"],
["Peru","PE"],
["Philippines","PH"],
["Poland","PL"],
["Portugal","PT"],
["Qatar","QA"],
["Romania","RO"],
["Rwanda","RW"],
["Saudi Arabia","SA"],
["Senegal","SN"],
["Serbia","RS"],
["Sierra Leone","SL"],
["Singapore","SG"],
["Slovakia","SK"],
["Slovenia","SI"],
["Somalia","SO"],
["South Africa","ZA"],
["South Korea","KR"],
["Spain","ES"],
["Sri Lanka","LK"],
["Sudan","SD"],
["Suriname","SR"],
["Sweden","SE"],
["Switzerland","CH"],
["Taiwan","TW"],
["Tajikistan","TJ"],
["Tanzania","TZ"],
["Thailand","TH"],
["Togo","TG"],
["Trinidad and Tobago","TT"],
["Tunisia","TN"],
["Türkiye","TR"],
["Uganda","UG"],
["Ukraine","UA"],
["United Arab Emirates","AE"],
["United Kingdom","GB"],
["United States","US"],
["Uruguay","UY"],
["Uzbekistan","UZ"],
["Venezuela","VE"],
["Viet Nam","VN"],
["Yemen","YE"],
["Zambia","ZM"],
["Zimbabwe","ZW"]
];
